# Import model modules so SQLAlchemy can resolve string relationships and register metadata.
from . import academy as _academy
from . import achievements as _achievements
from . import activity as _activity
from . import admin_config as _admin_config
from . import announcements as _announcements
from . import aviation as _aviation
from . import body_metrics as _body_metrics
from . import certification as _certification
from . import challenges as _challenges
from . import clearance as _clearance
from . import client as _client
from . import coach as _coach
from . import comments as _comments
from . import competition as _competition
from . import creator as _creator
from . import daily_log as _daily_log
from . import disaster as _disaster
from . import drill as _drill
from . import enterprise as _enterprise
from . import federation as _federation
from . import goals as _goals
from . import groups as _groups
from . import hardware as _hardware
from . import hazmat as _hazmat
from . import hydration as _hydration
from . import injury as _injury
from . import instructor as _instructor
from . import invite as _invite
from . import k9 as _k9
from . import ladder as _ladder
from . import listing as _listing
from . import live as _live
from . import loadout as _loadout
from . import login_log as _login_log
from . import macros as _macros
from . import maritime as _maritime
from . import meals as _meals
from . import messages as _messages
from . import mission_replay as _mission_replay
from . import nutrition as _nutrition
from . import org as _org
from . import periodization as _periodization
from . import plan as _plan
from . import posts as _posts
from . import pr_records as _pr_records
from . import progress_snapshot as _progress_snapshot
from . import pt as _pt
from . import rating as _rating
from . import reactions as _reactions
from . import recipes as _recipes
from . import recovery as _recovery
from . import recovery_progress as _recovery_progress
from . import recovery_protocol as _recovery_protocol
from . import recovery_stage as _recovery_stage
from . import recruit as _recruit
from . import rep_logs as _rep_logs
from . import scenario as _scenario
from . import schedule as _schedule
from . import search_rescue as _search_rescue
from . import season as _season
from . import sleep as _sleep
from . import sof as _sof
from . import sports_log as _sports_log
from . import strength_metric as _strength_metric
from . import swat as _swat
from . import tactical_drill as _tactical_drill
from . import team as _team
from . import tenant as _tenant
from . import tournament as _tournament
from . import unit as _unit
from . import user as _user
from . import weight as _weight
from . import wildland as _wildland
from . import workout_log as _workout_log

from . import user_profile as _user_profile
from . import coach_team_membership as _coach_team_membership
